//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayerLogicData.ServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.serviceitSoap")]
    public interface serviceitSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet GetDataSet(string tenthutuc, string[] thamso, object[] giatri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetAsync(string tenthutuc, string[] thamso, object[] giatri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcuteProcedureSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int ExcuteProcedureSQL(string tenthutuc, string[] thamso, object[] giatri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcuteProcedureSQL", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ExcuteProcedureSQLAsync(string tenthutuc, string[] thamso, object[] giatri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoUpdateDatabase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void AutoUpdateDatabase(System.Data.DataTable dt, string procedureName, string[] parameter, object[] value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoUpdateDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task AutoUpdateDatabaseAsync(System.Data.DataTable dt, string procedureName, string[] parameter, object[] value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviceitSoapChannel : LayerLogicData.ServiceReference.serviceitSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviceitSoapClient : System.ServiceModel.ClientBase<LayerLogicData.ServiceReference.serviceitSoap>, LayerLogicData.ServiceReference.serviceitSoap {
        
        public serviceitSoapClient() {
        }
        
        public serviceitSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviceitSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceitSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceitSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDataSet(string tenthutuc, string[] thamso, object[] giatri) {
            return base.Channel.GetDataSet(tenthutuc, thamso, giatri);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetAsync(string tenthutuc, string[] thamso, object[] giatri) {
            return base.Channel.GetDataSetAsync(tenthutuc, thamso, giatri);
        }
        
        public int ExcuteProcedureSQL(string tenthutuc, string[] thamso, object[] giatri) {
            return base.Channel.ExcuteProcedureSQL(tenthutuc, thamso, giatri);
        }
        
        public System.Threading.Tasks.Task<int> ExcuteProcedureSQLAsync(string tenthutuc, string[] thamso, object[] giatri) {
            return base.Channel.ExcuteProcedureSQLAsync(tenthutuc, thamso, giatri);
        }
        
        public void AutoUpdateDatabase(System.Data.DataTable dt, string procedureName, string[] parameter, object[] value) {
            base.Channel.AutoUpdateDatabase(dt, procedureName, parameter, value);
        }
        
        public System.Threading.Tasks.Task AutoUpdateDatabaseAsync(System.Data.DataTable dt, string procedureName, string[] parameter, object[] value) {
            return base.Channel.AutoUpdateDatabaseAsync(dt, procedureName, parameter, value);
        }
    }
}
